{{ if .Values.knightcrawler.qbitcollector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-qbitcollector'
  labels:
    component: qbitcollector
    project: '{{ .Chart.Name }}'
    release: '{{ .Release.Name }}'
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "4"
spec:
  replicas: {{ .Values.knightcrawler.qbitcollector.replicas }}
  selector:
    matchLabels:
      component: qbitcollector
      release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        component: qbitcollector
        release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: qbitcollector
          image: '{{ .Values.knightcrawler.qbitcollector.image }}{{ if ne .Values.knightcrawler.globalImageTagOverride "" }}:{{ .Values.knightcrawler.globalImageTagOverride }}{{else}}:{{ .Values.knightcrawler.qbitcollector.tag}}{{ end }}'
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-config'
            - secretRef:
                name: '{{ .Release.Name }}-secrets'
{{- end -}}