version: '3.8'
volumes:
  mongo-data: {}
  postgres-data: {}

services:
  mongodb:
    restart: unless-stopped
    image: bitnami/mongodb
    volumes:
      - mongo-data:/bitnami/mongodb
  
  scraper:
    restart: unless-stopped
    image: ghcr.io/kubo6472/torrentio-ghcr:scraper
    environment:
      - PORT=7001
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:5432/torrentio
      - ENABLE_SYNC=true
  
  torrentio:
    restart: unless-stopped
    image: ghcr.io/kubo6472/torrentio-ghcr:addon
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:5432/torrentio
      - ENABLE_SYNC=true
  
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=torrentio
