---

version: '3.9'
name: torrentio-self-host

services:

  mongodb:
    restart: unless-stopped
    ## This image does not support linux/arm64
    ## If you are using linux/arm64 (for example, a Raspberry Pi)
    ## then change the below line to:
    # image: mongo:6.0
    image: docker.io/bitnami/mongodb:7.0
    ports:
      - "27017:27017"
    volumes:
      ## If you have changed the image above please change this volume mounting too:
      # - mongo-data:/data/db
      - mongo-data:/bitnami/mongodb
  
  scraper:
    build: ./scraper
    restart: unless-stopped
    depends_on:
      - mongodb
      - postgres
    environment:
      - PORT=7001
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:5432/torrentio
      - ENABLE_SYNC=true
  
  torrentio:
    build: ./addon
    restart: unless-stopped
    depends_on:
      - mongodb
      - postgres
    ports:
      - "7000:7000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:5432/torrentio
      - ENABLE_SYNC=true
  
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=torrentio
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    ports:
      - 8191:8191

volumes:
  mongo-data:
  postgres-data:
