---

version: '3.9'
name: torrentio-self-host

services:

  mongodb:
    restart: unless-stopped
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/bitnami/mongodb
  
  scraper:
    build: ./scraper
    restart: unless-stopped
    environment:
      - PORT=7001
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:5432/torrentio
      - ENABLE_SYNC=true
  
  torrentio:
    build: ./addon
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/torrentio
      - DATABASE_URI=postgres://postgres@postgres:5432/torrentio
      - ENABLE_SYNC=true
  
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=torrentio

volumes:
  mongo-data:
  postgres-data:
