{{ if .Values.infrastructure.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-postgres'
  labels:
    component: postgres
    project: '{{ .Chart.Name }}'
    release: '{{ .Release.Name }}'
spec:
  selector:
    component: postgres
    release: '{{ .Release.Name }}'
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
{{- end -}}