apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-addon'
  labels:
    component: addon
    project: '{{ .Chart.Name }}'
    release: '{{ .Release.Name }}'
spec:
  selector:
    component: addon
    release: '{{ .Release.Name }}'
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
