name: Build and Push Tissue Service

on:
  push:
    paths:
      - 'src/tissue/**'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  process:
    uses: ./.github/workflows/base_image_workflow.yaml
    secrets: inherit
    with:
      CONTEXT: ./src/tissue/
      IMAGE_NAME: knightcrawler-tissue
