name: Build and Push Metadata Service

on:
  push:
    paths:
      - 'src/metadata/**'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  process:
    uses: ./.github/workflows/base_image_workflow.yaml
    secrets: inherit
    with:
      CONTEXT: ./src/metadata/
      DOCKERFILE: ./src/metadata/Dockerfile
      IMAGE_NAME: knightcrawler-metadata
