name: Build and Push Consumer Service

on:
  push:
    paths:
      - 'src/torrent-consumer/**'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  process:
    uses: ./.github/workflows/base_image_workflow.yaml
    secrets: inherit
    with:
      CONTEXT: ./src/
      DOCKERFILE: ./src/torrent-consumer/Dockerfile
      IMAGE_NAME: knightcrawler-consumer
