name: Build and Push Addon Service

on:
  push:
    paths:
      - 'src/node/addon/**'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  process:
    uses: ./.github/workflows/base_image_workflow.yaml
    secrets: inherit
    with:
      CONTEXT: ./src/node/addon/
      IMAGE_NAME: knightcrawler-addon
