name: Build and Push Jackett Addon Service

on:
  push:
    paths:
      - 'src/node/addon-jackett/**'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  process:
    uses: ./.github/workflows/base_image_workflow.yaml
    secrets: inherit
    with:
      CONTEXT: ./src/node/addon-jackett/
      IMAGE_NAME: knightcrawler-addon-jackett
