name: Build and Push Consumer Service

on:
  push:
    paths:
      - 'src/consumer/**'
  workflow_dispatch:

jobs:
  process:
    uses: ./.github/workflows/base_image_workflow.yaml
    secrets: inherit
    with:
      CONTEXT: ./src/consumer/
      IMAGE_NAME: knightcrawler-consumer
