name: Build and Push Producer Service

on:
  push:
    paths:
      - 'src/producer/**'
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  process:
    uses: ./.github/workflows/base_image_workflow.yaml
    secrets: inherit
    with:
      CONTEXT: ./src/
      DOCKERFILE: ./src/producer/src/Dockerfile
      IMAGE_NAME: knightcrawler-producer
