name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push scraper
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:scraper"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:scraper
      - name: Build and push addon
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:addon"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:addon
